name: Build & Publish

on:
  schedule:
    - cron: "0 12 * * 1"
  push:
    branches:
      - main
  repository_dispatch:
    types: [definition_update]
  workflow_dispatch:

jobs:
  build_assets:
    runs-on: ubuntu-latest
    name: Build VIA assets
    outputs:
      via-build-artifact: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: the-via/app
          fetch-depth: 0
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: |
          bun install
          bun run refresh-kbs
      - name: Apply patches
        run: |
          sed -i 's|^\(\s*\)//\(.*fetch.*\)|\1\2|; s|^\(\s*\)\(const hash = document.getElementById.*\)|\1//\2|' src/utils/device-store.ts
          sed -i 's/dispatch(loadStoredCustomDefinitions/await dispatch(loadStoredCustomDefinitions/' src/store/devicesThunks.ts
      - name: Build
        run: bun run build
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: via-build
          path: dist/
          retention-days: 1

  build:
    needs: build_assets
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: Build VIA-desktop
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.build_assets.outputs.via-build-artifact }}
      - run: mv via-build/ public/
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Set version to today
        run: npm version $(date +'%Y.%m.%d') --no-git-tag-version
      - name: Build for ${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- --arch ${{ matrix.arch }}
